CREACIÓN DEL DATASET DE NO INCENDIOS

In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from geopy.geocoders import Nominatim 
import geopandas as gpd
from shapely.geometry import Polygon, Point
import random
from datetime import datetime, timedelta

In [2]:
#!pip install geopandas

In [3]:
"""OJO NO EJECUTAR (TARDA MUCHO)"""
"""OJO NO EJECUTAR (TARDA MUCHO)"""
"""OJO NO EJECUTAR (TARDA MUCHO)"""
"""OJO NO EJECUTAR (TARDA MUCHO)"""
"""OJO NO EJECUTAR (TARDA MUCHO)"""
"""OJO NO EJECUTAR (TARDA MUCHO)"""
"""OJO NO EJECUTAR (TARDA MUCHO)"""
"""OJO NO EJECUTAR (TARDA MUCHO)"""
"""OJO NO EJECUTAR (TARDA MUCHO)"""
"""OJO NO EJECUTAR (TARDA MUCHO)"""
"""OJO NO EJECUTAR (TARDA MUCHO)"""
"""OJO NO EJECUTAR (TARDA MUCHO)"""


# Cargar el archivo que contiene los límites de Galicia (shapefile, GeoJSON, etc.)
datos_galicia = gpd.read_file('Data/map_spain/galicia.geojson')  

# Obtener el límite de Galicia (podría ser una sola geometría o múltiples)
limite_galicia = datos_galicia.geometry.unary_union

# Función para generar coordenadas aleatorias dentro del límite de Galicia
def generar_coordenadas_random():
    while True:
        # Generar coordenadas aleatorias dentro de un rango específico
        latitud = random.uniform(limite_galicia.bounds[1], limite_galicia.bounds[3])
        longitud = random.uniform(limite_galicia.bounds[0], limite_galicia.bounds[2])
        
        # Crear un punto con las coordenadas aleatorias
        punto = Point(longitud, latitud)
        
        # Verificar si el punto está dentro del límite de Galicia
        if punto.within(limite_galicia):
            return punto

# Generar 10 coordenadas aleatorias dentro de Galicia con barra de progreso
coordenadas_random_galicia = []
for _ in tqdm(range(10000), desc='Generando coordenadas'):
    coordenadas_random_galicia.append(generar_coordenadas_random())

# Convertir las coordenadas a un DataFrame
df_coordenadas = pd.DataFrame({'Longitud': [p.x for p in coordenadas_random_galicia],
                               'Latitud': [p.y for p in coordenadas_random_galicia]})

# Guardar el DataFrame con las coordenadas en un archivo CSV
df_coordenadas.to_csv('Data/map_spain/coordenadas_galicia.csv', index=False)

print("Se han guardado las coordenadas en 'Data/map_spain/coordenadas_galicia.csv'")

Generando coordenadas: 100%|██████████| 10000/10000 [00:01<00:00, 7256.89it/s]

Se han guardado las coordenadas en 'Data/map_spain/coordenadas_galicia.csv'

In [4]:
df = df_coordenadas
df

      Longitud    Latitud
0    -7.635567  42.638641
1    -8.112795  42.715676
2    -7.825316  42.816622
3    -7.761559  42.102438
4    -8.960688  43.270629
...        ...        ...
9995 -8.277369  42.291368
9996 -6.890266  43.020213
9997 -7.600368  43.600801
9998 -8.695600  43.089310
9999 -7.022182  42.233426

[10000 rows x 2 columns]

In [5]:
# Inicializar el geolocalizador
geolocator = Nominatim(user_agent="prediccion_incendios")

# Definir la función para obtener la ubicación
def get_location(row):
    location = geolocator.reverse(f"{row['Latitud']}, {row['Longitud']}")
    return location

# Aplicar la función para obtener la información de ubicación
tqdm.pandas()
df['location_info'] = df.progress_apply(get_location, axis=1)

# Definir funciones para obtener provincia y municipio
def obtener_provincia(loc):
    if loc is not None and loc.raw.get('address'):
        return loc.raw.get('address', {}).get('state', '')
    else:
        return ''

def obtener_municipio(loc):
    if loc is not None and loc.raw.get('address'):
        return loc.raw.get('address', {}).get('city', '')
    else:
        return ''

# Aplicar las funciones para obtener provincia y municipio
df['provincia'] = df['location_info'].apply(obtener_provincia)
df['municipio'] = df['location_info'].apply(obtener_municipio)

# Mostrar el DataFrame resultante
print(df)

df.to_csv('Data/data_Galicia/intermedios/neg_gal.csv', index=False)

100%|██████████| 10000/10000 [1:23:51<00:00,  1.99it/s]

      Longitud    Latitud                                      location_info  \
0    -7.635567  42.638641  (Gudín, Eirexafeita, O Saviñao, Terra de Lemos...
1    -8.112795  42.715676  (Erbo de Abaixo, O Cello, Lalín, O Deza, Ponte...
2    -7.825316  42.816622  (LU-P-3301, O Lugar de Roán, A Lucencia, Cumbr...
3    -7.761559  42.102438  (Couso de Limia, Sandiás, A Limia, Ourense, Ga...
4    -8.960688  43.270629  (DP-6804, O Porto de Corme, As Regadiñas, Corm...
...        ...        ...                                                ...
9995 -8.277369  42.291368  (Boca dos Acevedos, Prado, Covelo, A Paradanta...
9996 -6.890266  43.020213  (Liares, Ibias, Asturias / Asturies, España, (...
9997 -7.600368  43.600801  (Os Rubeiras, Merille, Ourol, A Mariña Occiden...
9998 -8.695600  43.089310  (AC-400, O Carballal, Erbecedo, Coristanco, Be...
9999 -7.022182  42.233426  (A Curbaceira, Corzos, A Veiga, Valdeorras, Ou...

                provincia  municipio
0                 Galicia  O Saviñao
1                 Galicia
2                 Galicia
3                 Galicia
4                 Galicia
...                   ...        ...
9995              Galicia
9996  Asturias / Asturies      Ibias
9997              Galicia
9998              Galicia
9999              Galicia

[10000 rows x 5 columns]

In [6]:
"""A PARTIR DE AQUÍ YA SE PUEDE"""
"""A PARTIR DE AQUÍ YA SE PUEDE"""
"""A PARTIR DE AQUÍ YA SE PUEDE"""
"""A PARTIR DE AQUÍ YA SE PUEDE"""
"""A PARTIR DE AQUÍ YA SE PUEDE"""
"""A PARTIR DE AQUÍ YA SE PUEDE"""
"""A PARTIR DE AQUÍ YA SE PUEDE"""
"""A PARTIR DE AQUÍ YA SE PUEDE"""
"""A PARTIR DE AQUÍ YA SE PUEDE"""
"""A PARTIR DE AQUÍ YA SE PUEDE"""
"""A PARTIR DE AQUÍ YA SE PUEDE"""


df = pd.read_csv("Data/data_Galicia/intermedios/neg_gal.csv")

In [7]:
df

,Longitud,Latitud,location_info,provincia,municipio
0,-7.635567,42.638641,"Gudín, Eirexafeita, O Saviñao, Terra de Lemos,...",Galicia,O Saviñao
1,-8.112795,42.715676,"Erbo de Abaixo, O Cello, Lalín, O Deza, Pontev...",Galicia,NaN
2,-7.825316,42.816622,"LU-P-3301, O Lugar de Roán, A Lucencia, Cumbra...",Galicia,NaN
3,-7.761559,42.102438,"Couso de Limia, Sandiás, A Limia, Ourense, Gal...",Galicia,NaN
4,-8.960688,43.270629,"DP-6804, O Porto de Corme, As Regadiñas, Corme...",Galicia,NaN
...,...,...,...,...,...
9995,-8.277369,42.291368,"Boca dos Acevedos, Prado, Covelo, A Paradanta,...",Galicia,NaN
9996,-6.890266,43.020213,"Liares, Ibias, Asturias / Asturies, España",Asturias / Asturies,Ibias
9997,-7.600368,43.600801,"Os Rubeiras, Merille, Ourol, A Mariña Occident...",Galicia,NaN
9998,-8.695600,43.089310,"AC-400, O Carballal, Erbecedo, Coristanco, Ber...",Galicia,NaN
9999,-7.022182,42.233426,"A Curbaceira, Corzos, A Veiga, Valdeorras, Our...",Galicia,NaN

In [8]:
# Filtrar filas donde 'location_info' no sea nulo y contenga 'Galicia' (sin distinguir mayúsculas y minúsculas)
df_galicia = df[df['location_info'].notnull() & df['location_info'].str.contains('Galicia', case=False)]

In [9]:
df = df_galicia
df_galicia

,Longitud,Latitud,location_info,provincia,municipio
0,-7.635567,42.638641,"Gudín, Eirexafeita, O Saviñao, Terra de Lemos,...",Galicia,O Saviñao
1,-8.112795,42.715676,"Erbo de Abaixo, O Cello, Lalín, O Deza, Pontev...",Galicia,NaN
2,-7.825316,42.816622,"LU-P-3301, O Lugar de Roán, A Lucencia, Cumbra...",Galicia,NaN
3,-7.761559,42.102438,"Couso de Limia, Sandiás, A Limia, Ourense, Gal...",Galicia,NaN
4,-8.960688,43.270629,"DP-6804, O Porto de Corme, As Regadiñas, Corme...",Galicia,NaN
...,...,...,...,...,...
9994,-7.453686,41.866827,"Tamaguelos, San Cibrao, Verín, Ourense, Galici...",Galicia,NaN
9995,-8.277369,42.291368,"Boca dos Acevedos, Prado, Covelo, A Paradanta,...",Galicia,NaN
9997,-7.600368,43.600801,"Os Rubeiras, Merille, Ourol, A Mariña Occident...",Galicia,NaN
9998,-8.695600,43.089310,"AC-400, O Carballal, Erbecedo, Coristanco, Ber...",Galicia,NaN
9999,-7.022182,42.233426,"A Curbaceira, Corzos, A Veiga, Valdeorras, Our...",Galicia,NaN

In [10]:
from geopy.geocoders import Nominatim
import pandas as pd
from tqdm import tqdm

df = df[df['location_info'].notnull()]


# Lista de provincias españolas
provincias_espanolas = ['A Coruña', 'Lugo','Ourense','Pontevedra']

# Suponiendo que tienes un DataFrame llamado 'df' con la columna 'location_info' generada previamente

def actualizar_provincia(row):
    matching_provinces = [provincia for provincia in provincias_espanolas if provincia in row['location_info']]
    if len(matching_provinces) == 1:
        return matching_provinces[0]
    else:
        return pd.NA if len(matching_provinces) == 0 else 'Multiple'  # Devuelve NaN si no hay coincidencias, 'Multiple' si hay más de una

# Aplicar la función para actualizar la columna 'provincia'
df['provincia'] = df.apply(actualizar_provincia, axis=1)

# Eliminar las filas con múltiples coincidencias o sin coincidencias
df = df[df['provincia'].notna()]

# Mostrar el DataFrame con la columna 'provincia' actualizada
print(df[['Latitud', 'Longitud', 'provincia']])

# Guardar el DataFrame modificado como un archivo CSV
df.to_csv('Data/data_Galicia/intermedios/neg_gal_prov.csv', index=False)

        Latitud  Longitud   provincia
0     42.638641 -7.635567        Lugo
1     42.715676 -8.112795  Pontevedra
2     42.816622 -7.825316        Lugo
3     42.102438 -7.761559     Ourense
4     43.270629 -8.960688    A Coruña
...         ...       ...         ...
9994  41.866827 -7.453686     Ourense
9995  42.291368 -8.277369  Pontevedra
9997  43.600801 -7.600368        Lugo
9998  43.089310 -8.695600    A Coruña
9999  42.233426 -7.022182     Ourense

[8426 rows x 3 columns]

In [11]:
# Crear un DataFrame vacío con las columnas especificadas
columnas = ['latitude', 'longitude', 'brightness', 'scan', 'track', 'acq_date', 'acq_time', 'satellite', 'instrument', 'confidence', 'version', 'bright_t31', 'frp', 'daynight', 'type', 'location_info', 'Provincia', 'Comunidad_Autonoma']

df = pd.DataFrame(columns=columnas)

In [12]:
df1 = pd.read_csv("Data/data_Galicia/intermedios/neg_gal_prov.csv")
df1

,Longitud,Latitud,location_info,provincia,municipio
0,-7.635567,42.638641,"Gudín, Eirexafeita, O Saviñao, Terra de Lemos,...",Lugo,O Saviñao
1,-8.112795,42.715676,"Erbo de Abaixo, O Cello, Lalín, O Deza, Pontev...",Pontevedra,NaN
2,-7.825316,42.816622,"LU-P-3301, O Lugar de Roán, A Lucencia, Cumbra...",Lugo,NaN
3,-7.761559,42.102438,"Couso de Limia, Sandiás, A Limia, Ourense, Gal...",Ourense,NaN
4,-8.960688,43.270629,"DP-6804, O Porto de Corme, As Regadiñas, Corme...",A Coruña,NaN
...,...,...,...,...,...
8421,-7.453686,41.866827,"Tamaguelos, San Cibrao, Verín, Ourense, Galici...",Ourense,NaN
8422,-8.277369,42.291368,"Boca dos Acevedos, Prado, Covelo, A Paradanta,...",Pontevedra,NaN
8423,-7.600368,43.600801,"Os Rubeiras, Merille, Ourol, A Mariña Occident...",Lugo,NaN
8424,-8.695600,43.089310,"AC-400, O Carballal, Erbecedo, Coristanco, Ber...",A Coruña,NaN
8425,-7.022182,42.233426,"A Curbaceira, Corzos, A Veiga, Valdeorras, Our...",Ourense,NaN

In [13]:
# Mapeo de columnas entre los DataFrames actualizado
mapeo_columnas = {
    'latitude': 'Latitud',
    'longitude': 'Longitud',
    'location_info': 'location_info',
    'Provincia': 'provincia',
    'municipio': 'municipio'
}

# Rellenar las columnas correspondientes en df con los datos de df1
for columna_df, columna_df1 in mapeo_columnas.items():
    df[columna_df] = df1[columna_df1]

# Verificar el resultado
df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,location_info,Provincia,Comunidad_Autonoma,municipio
0,42.638641,-7.635567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Gudín, Eirexafeita, O Saviñao, Terra de Lemos,...",Lugo,NaN,O Saviñao
1,42.715676,-8.112795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Erbo de Abaixo, O Cello, Lalín, O Deza, Pontev...",Pontevedra,NaN,NaN
2,42.816622,-7.825316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LU-P-3301, O Lugar de Roán, A Lucencia, Cumbra...",Lugo,NaN,NaN
3,42.102438,-7.761559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Couso de Limia, Sandiás, A Limia, Ourense, Gal...",Ourense,NaN,NaN
4,43.270629,-8.960688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DP-6804, O Porto de Corme, As Regadiñas, Corme...",A Coruña,NaN,NaN

In [14]:
print(df.columns)
print(df1.columns)

Index(['latitude', 'longitude', 'brightness', 'scan', 'track', 'acq_date',
       'acq_time', 'satellite', 'instrument', 'confidence', 'version',
       'bright_t31', 'frp', 'daynight', 'type', 'location_info', 'Provincia',
       'Comunidad_Autonoma', 'municipio'],
      dtype='object')
Index(['Longitud', 'Latitud', 'location_info', 'provincia', 'municipio'], dtype='object')

Añadir la estación metereológica más cercana a cada punto

In [15]:
from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="prediccion_incendios")

lugares = ["Val do Dubra, A Coruña, Spain", "Boiro, A Coruña, Spain","Lousame, A Coruña, Spain","Narón, A Coruña, Spain", 
           "Castrelo de Miño, Ourense, Spain", "A Veiga, Ourense, Spain", "Calvos de Randin, Ourense, Spain", "Ríos, Ourense, Spain",
           "Baleira, Lugo, Spain", "Mondoñedo, Lugo, Spain", "Antas de Ulla, Lugo, Spain", "Chantada, Lugo, Spain", 
            "Ponteareas, Pontevedra, Spain", "Meis, Pontevedra, Spain",  "O Rosal, Pontevedra, Spain", "Lalín, Pontevedra, Spain"]

coordenadas = {}

for lugar in lugares:
    # Dividir la cadena en partes separadas por comas y obtener el primer elemento (el nombre del pueblo)
    nombre_pueblo = lugar.split(',')[0]
    
    location = geolocator.geocode(lugar)
    if location:
        # Usar solo el nombre del pueblo como clave en el diccionario
        coordenadas[nombre_pueblo] = (location.latitude, location.longitude)

# Mostrar el diccionario con los nombres de los pueblos y sus coordenadas
print(coordenadas)

{'Val do Dubra': (43.0101545, -8.6516271), 'Boiro': (42.6823024, -8.8909873), 'Lousame': (42.7733607, -8.832957073089341), 'Narón': (43.5010981, -8.1923091), 'Castrelo de Miño': (42.2965639, -8.065678393458727), 'A Veiga': (42.2507678, -7.0260508), 'Calvos de Randin': (41.92502975, -7.859098930350559), 'Ríos': (41.9745769, -7.2823706), 'Baleira': (43.05400255, -7.228073882860878), 'Mondoñedo': (43.4296687, -7.3638814), 'Antas de Ulla': (42.7674234, -7.8984065), 'Chantada': (42.6089783, -7.8218597), 'Ponteareas': (42.1741836, -8.5050427), 'Meis': (42.4996133, -8.724936507774776), 'O Rosal': (41.936991, -8.8370358), 'Lalín': (42.6513299, -8.154379)}

In [16]:
from geopy.distance import geodesic

# Crear una función para encontrar la estación más cercana
def estacion_mas_cercana(row):
    distancias = {}
    for lugar, coordenada in coordenadas.items():
        distancias[lugar] = geodesic((row['latitude'], row['longitude']), coordenada).kilometers
    estacion_cercana = min(distancias, key=distancias.get)
    return estacion_cercana

# Aplicar la función a cada fila del DataFrame para encontrar la estación más cercana
df['Estacion'] = ''

for idx, row in tqdm(df.iterrows(), total=len(df)):
    df.at[idx, 'Estacion'] = estacion_mas_cercana(row)

# Guardar el DataFrame en un archivo sobrescribiendo si ya existe
archivo_salida = 'Data/data_Galicia/intermedios/neg_gal_prov.csv'  # Reemplaza 'nombre_del_archivo.csv' con el nombre de tu archivo de salida
df.to_csv(archivo_salida, index=False, mode='w')

print(f"Archivo guardado en: {archivo_salida}")

100%|██████████| 8426/8426 [00:21<00:00, 400.55it/s]

Archivo guardado en: Data/data_Galicia/intermedios/neg_gal_prov.csv

In [17]:
df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,location_info,Provincia,Comunidad_Autonoma,municipio,Estacion
0,42.638641,-7.635567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Gudín, Eirexafeita, O Saviñao, Terra de Lemos,...",Lugo,NaN,O Saviñao,Chantada
1,42.715676,-8.112795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Erbo de Abaixo, O Cello, Lalín, O Deza, Pontev...",Pontevedra,NaN,NaN,Lalín
2,42.816622,-7.825316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LU-P-3301, O Lugar de Roán, A Lucencia, Cumbra...",Lugo,NaN,NaN,Antas de Ulla
3,42.102438,-7.761559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Couso de Limia, Sandiás, A Limia, Ourense, Gal...",Ourense,NaN,NaN,Calvos de Randin
4,43.270629,-8.960688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DP-6804, O Porto de Corme, As Regadiñas, Corme...",A Coruña,NaN,NaN,Val do Dubra

In [18]:
# Asignar el valor "Galicia" a todas las celdas de la columna 'Comunidad_Autonoma'
df['Comunidad_Autonoma'] = 'Galicia'

# Verificar el cambio
df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,location_info,Provincia,Comunidad_Autonoma,municipio,Estacion
0,42.638641,-7.635567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Gudín, Eirexafeita, O Saviñao, Terra de Lemos,...",Lugo,Galicia,O Saviñao,Chantada
1,42.715676,-8.112795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Erbo de Abaixo, O Cello, Lalín, O Deza, Pontev...",Pontevedra,Galicia,NaN,Lalín
2,42.816622,-7.825316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LU-P-3301, O Lugar de Roán, A Lucencia, Cumbra...",Lugo,Galicia,NaN,Antas de Ulla
3,42.102438,-7.761559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Couso de Limia, Sandiás, A Limia, Ourense, Gal...",Ourense,Galicia,NaN,Calvos de Randin
4,43.270629,-8.960688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DP-6804, O Porto de Corme, As Regadiñas, Corme...",A Coruña,Galicia,NaN,Val do Dubra

In [19]:
# Definir la función para generar fechas aleatorias
def generar_fechas_aleatorias(inicio, fin, cantidad):
    inicio = datetime.strptime(inicio, '%Y-%m-%d')
    fin = datetime.strptime(fin, '%Y-%m-%d')
    delta = fin - inicio
    fechas_aleatorias = [inicio + timedelta(days=random.randint(0, delta.days)) for _ in range(cantidad)]
    return fechas_aleatorias

# Generar fechas aleatorias
fechas_aleatorias = generar_fechas_aleatorias('2008-01-01', '2023-12-31', len(df))

# Asignar las fechas aleatorias al DataFrame
df['acq_date'] = fechas_aleatorias

# Verificar el resultado

df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,location_info,Provincia,Comunidad_Autonoma,municipio,Estacion
0,42.638641,-7.635567,NaN,NaN,NaN,2023-11-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Gudín, Eirexafeita, O Saviñao, Terra de Lemos,...",Lugo,Galicia,O Saviñao,Chantada
1,42.715676,-8.112795,NaN,NaN,NaN,2012-02-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Erbo de Abaixo, O Cello, Lalín, O Deza, Pontev...",Pontevedra,Galicia,NaN,Lalín
2,42.816622,-7.825316,NaN,NaN,NaN,2023-09-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LU-P-3301, O Lugar de Roán, A Lucencia, Cumbra...",Lugo,Galicia,NaN,Antas de Ulla
3,42.102438,-7.761559,NaN,NaN,NaN,2012-07-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Couso de Limia, Sandiás, A Limia, Ourense, Gal...",Ourense,Galicia,NaN,Calvos de Randin
4,43.270629,-8.960688,NaN,NaN,NaN,2017-08-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DP-6804, O Porto de Corme, As Regadiñas, Corme...",A Coruña,Galicia,NaN,Val do Dubra

In [20]:

# Función para generar horas y minutos aleatorios
def generar_horas_aleatorias(cantidad):
    horas_aleatorias = [f"{random.randint(0, 23):02d}{random.randint(0, 59):02d}" for _ in range(cantidad)]
    return horas_aleatorias

# Generar horas y minutos aleatorios
horas_aleatorias = generar_horas_aleatorias(len(df))

# Asignar las horas y minutos aleatorios al DataFrame
df['acq_time'] = horas_aleatorias

# Verificar el resultado
df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,location_info,Provincia,Comunidad_Autonoma,municipio,Estacion
0,42.638641,-7.635567,NaN,NaN,NaN,2023-11-12,1124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Gudín, Eirexafeita, O Saviñao, Terra de Lemos,...",Lugo,Galicia,O Saviñao,Chantada
1,42.715676,-8.112795,NaN,NaN,NaN,2012-02-06,0348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Erbo de Abaixo, O Cello, Lalín, O Deza, Pontev...",Pontevedra,Galicia,NaN,Lalín
2,42.816622,-7.825316,NaN,NaN,NaN,2023-09-14,2145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LU-P-3301, O Lugar de Roán, A Lucencia, Cumbra...",Lugo,Galicia,NaN,Antas de Ulla
3,42.102438,-7.761559,NaN,NaN,NaN,2012-07-02,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Couso de Limia, Sandiás, A Limia, Ourense, Gal...",Ourense,Galicia,NaN,Calvos de Randin
4,43.270629,-8.960688,NaN,NaN,NaN,2017-08-17,0615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DP-6804, O Porto de Corme, As Regadiñas, Corme...",A Coruña,Galicia,NaN,Val do Dubra

In [21]:
import random

# Generar valores aleatorios de 'D' y 'N' para la columna 'daynight'
df['daynight'] = ['D' if random.randint(0, 1) == 0 else 'N' for _ in range(len(df))]

# Verificar el resultado
df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,location_info,Provincia,Comunidad_Autonoma,municipio,Estacion
0,42.638641,-7.635567,NaN,NaN,NaN,2023-11-12,1124,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,"Gudín, Eirexafeita, O Saviñao, Terra de Lemos,...",Lugo,Galicia,O Saviñao,Chantada
1,42.715676,-8.112795,NaN,NaN,NaN,2012-02-06,0348,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,"Erbo de Abaixo, O Cello, Lalín, O Deza, Pontev...",Pontevedra,Galicia,NaN,Lalín
2,42.816622,-7.825316,NaN,NaN,NaN,2023-09-14,2145,NaN,NaN,NaN,NaN,NaN,NaN,D,NaN,"LU-P-3301, O Lugar de Roán, A Lucencia, Cumbra...",Lugo,Galicia,NaN,Antas de Ulla
3,42.102438,-7.761559,NaN,NaN,NaN,2012-07-02,2001,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,"Couso de Limia, Sandiás, A Limia, Ourense, Gal...",Ourense,Galicia,NaN,Calvos de Randin
4,43.270629,-8.960688,NaN,NaN,NaN,2017-08-17,0615,NaN,NaN,NaN,NaN,NaN,NaN,D,NaN,"DP-6804, O Porto de Corme, As Regadiñas, Corme...",A Coruña,Galicia,NaN,Val do Dubra

In [22]:
# Lista de columnas a las que se les asignará el valor 0
columnas_cero = ['brightness', 'scan', 'track', 'confidence', 'bright_t31', 'frp', 'satellite','instrument', 'type' ]

# Asignar el valor 0 a las columnas especificadas en todas las filas
df[columnas_cero] = 0

# Verificar el resultado
df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,location_info,Provincia,Comunidad_Autonoma,municipio,Estacion
0,42.638641,-7.635567,0,0,0,2023-11-12,1124,0,0,0,NaN,0,0,N,0,"Gudín, Eirexafeita, O Saviñao, Terra de Lemos,...",Lugo,Galicia,O Saviñao,Chantada
1,42.715676,-8.112795,0,0,0,2012-02-06,0348,0,0,0,NaN,0,0,N,0,"Erbo de Abaixo, O Cello, Lalín, O Deza, Pontev...",Pontevedra,Galicia,NaN,Lalín
2,42.816622,-7.825316,0,0,0,2023-09-14,2145,0,0,0,NaN,0,0,D,0,"LU-P-3301, O Lugar de Roán, A Lucencia, Cumbra...",Lugo,Galicia,NaN,Antas de Ulla
3,42.102438,-7.761559,0,0,0,2012-07-02,2001,0,0,0,NaN,0,0,N,0,"Couso de Limia, Sandiás, A Limia, Ourense, Gal...",Ourense,Galicia,NaN,Calvos de Randin
4,43.270629,-8.960688,0,0,0,2017-08-17,0615,0,0,0,NaN,0,0,D,0,"DP-6804, O Porto de Corme, As Regadiñas, Corme...",A Coruña,Galicia,NaN,Val do Dubra

In [23]:
df.to_csv('Data/data_Galicia/intermedios/gal_neg_est.csv', index=False, mode='w')

In [27]:
import pandas as pd
import unicodedata
from tqdm.auto import tqdm

def normalizar_texto(texto):
    """Normaliza cadenas de texto eliminando tildes y caracteres especiales."""
    return unicodedata.normalize('NFKD', texto).encode('ascii', 'ignore').decode('ascii').lower()

def procesar_archivos(archivo_incendios, archivo_clima, archivo_salida):
    # Cargar los datos
    df_incendios = pd.read_csv(archivo_incendios)
    df_clima = pd.read_csv(archivo_clima)

    # Convertir las fechas a formato de fecha
    df_incendios['acq_date'] = pd.to_datetime(df_incendios['acq_date'])
    df_clima['Fecha'] = pd.to_datetime(df_clima['Fecha'])

    # Normalizar nombres de estaciones
    df_incendios['Estacion'] = df_incendios['Estacion'].apply(normalizar_texto)
    df_clima['Estacion'] = df_clima['Estacion'].apply(normalizar_texto)

    # Fusionar los datasets
    print("Combinando datasets...")
    df_combinado = pd.merge(df_incendios, df_clima, left_on=['acq_date', 'Estacion'], right_on=['Fecha', 'Estacion'], how='left')

    # Eliminar columnas redundantes y renombrar según sea necesario
    df_combinado.drop(columns=['Fecha_y'], inplace=True, errors='ignore')
    df_combinado.rename(columns={'Fecha_x': 'Fecha'}, inplace=True)

    # Guardar el archivo combinado
    df_combinado.to_csv(archivo_salida, index=False)
    print(f"Archivo combinado guardado en: {archivo_salida}")
    
    return df_combinado  # Retornar el DataFrame combinado

# Rutas de los archivos
archivo_incendios = 'Data/data_Galicia/intermedios/gal_neg_est.csv'
archivo_clima = 'Data/data_Galicia/clima_estaciones.csv'
archivo_salida = 'Data/data_Galicia/incen_gal_neg_est.csv'

# Ejecutar la función y capturar el DataFrame resultante
df_combinado = procesar_archivos(archivo_incendios, archivo_clima, archivo_salida)

# Agregar un print adicional
print("Proceso completado.")

# Imprimir el dataset resultante
print("Dataset resultante:")
df_combinado

Combinando datasets...
Archivo combinado guardado en: Data/data_Galicia/incen_gal_neg_est.csv
Proceso completado.
Dataset resultante:

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,Comunidad_Autonoma,municipio,Estacion,Fecha,Humedad foliar,Humedad relativa,Humedad suelo,Precipitación,Temperatura del suelo,Viento
0,42.638641,-7.635567,0,0,0,2023-11-12,1124,0,0,0,...,Galicia,O Saviñao,chantada,2023-11-12,2.2,88.0,9.8,0.0,15.2,1.2
1,42.715676,-8.112795,0,0,0,2012-02-06,348,0,0,0,...,Galicia,NaN,lalin,2012-02-06,10.0,80.0,0.2,2.8,5.5,12.9
2,42.816622,-7.825316,0,0,0,2023-09-14,2145,0,0,0,...,Galicia,NaN,antas de ulla,2023-09-14,2.9,81.0,0.1,0.0,18.4,2.2
3,42.102438,-7.761559,0,0,0,2012-07-02,2001,0,0,0,...,Galicia,NaN,calvos de randin,2012-07-02,8.8,72.0,-9999.0,0.1,16.5,4.9
4,43.270629,-8.960688,0,0,0,2017-08-17,615,0,0,0,...,Galicia,NaN,val do dubra,2017-08-17,1.1,90.0,0.1,0.6,20.2,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8421,41.866827,-7.453686,0,0,0,2012-03-13,528,0,0,0,...,Galicia,NaN,rios,2012-03-13,0.0,57.0,0.3,3.2,10.2,10.7
8422,42.291368,-8.277369,0,0,0,2018-07-30,1018,0,0,0,...,Galicia,NaN,castrelo de mino,2018-07-30,0.1,72.0,0.0,0.0,23.1,3.1
8423,43.600801,-7.600368,0,0,0,2016-02-06,247,0,0,0,...,Galicia,NaN,mondonedo,2016-02-06,10.4,88.0,0.5,27.8,8.7,4.9
8424,43.089310,-8.695600,0,0,0,2017-05-25,1702,0,0,0,...,Galicia,NaN,val do dubra,2017-05-25,4.1,96.0,0.2,14.4,17.3,7.2
8425,42.233426,-7.022182,0,0,0,2022-12-21,2220,0,0,0,...,Galicia,NaN,a veiga,2022-12-21,17.4,91.0,0.2,0.0,5.0,8.6